export const metadata = {
    title: 'About Page',
    description: 'Generated by create next app',
};

export default function About() {
    return (
        <main>
            <div>welcome to the about page</div>
        </main>
    );
}
