import Link from 'next/link';
import './globals.css';
import { Montserrat } from 'next/font/google';

const montserrat = Montserrat({
    weight: ['400', '700'],
    subsets: ['latin'],
    variable: '--font-montserrat',
});
export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={`${montserrat.className}`}>
                <nav>
                    <Link className="p-1" href={'/ssr'}>
                        Go to SSR
                    </Link>
                    <Link href={'/csr'}>Go to CSR</Link>
                    <Link href={'/'}>Go to Static</Link>
                    <Link href={'/apiexample'}>Go to API routes example</Link>
                </nav>
                {children}
            </body>
        </html>
    );
}
