import Link from 'next/link';
import './globals.css';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <nav>
                    <Link href={'/ssr'}>Go to SSR</Link>
                    <Link href={'/csr'}>Go to CSR</Link>
                    <Link href={'/'}>Go to Static</Link>
                </nav>
                {children}
            </body>
        </html>
    );
}
